# Disable sudo to speed up the build
sudo: false

language: python

# python versions to test
python:
  - "3.7.4"
  - "3.7-dev"

# test with pytest
script:
  - pytest

# install dependencies
install:
  - pip install typing_extensions
  - pip install codecov

# run the unit test
script:
  - coverage run tests.py

# push the results back to codecov
after_success:
  - codecov
